### ISSUE TITLE
Training data query

### ISSUE THREAD

**Issue by duhaime** [chrisjmccormick/MinHash#1]
Thanks so much for putting this post and code together @chrisjmccormick, this is great stuff.

I just have a quick query on the training data--where does this come from? I ask because I'm trying to tune an algorithm on this data but it looks like the *.truth files are missing some true positive matches (e.g. [u't8061', u't8071'] should be a match, but that pair isn't identified in articles_10000.truth). I've got many pairs with very high similarity scores that aren't identified in the truth files, which makes it tricky to measure the precision of the algorithm I'm tuning.

If you recall where the data came from, I'd be game to hunt down the origin and see if there are more true matches there. In any event, thanks again for this work!

**Comment by chrisjmccormick** [comment]
Hi duhaime,

I tried hunting around for the source of the dataset a while back and couldn't find it, then forgot to reply, sorry! I believe it was from a programming assignment from a course website.  I don't think I omitted any of the truth information--so if you found a pair that should be a match, then that's probably an error in the original dataset.

**Comment by duhaime** [comment]
Ah, I was afraid of that! It looks like there are ~1000 true positives that aren't identified as such in the training data. In any event, I'm grateful for your post and this work!
